<?php
/**
* value of the minimum age
*/ 
define('MIN_AGE', 0);

/**
* value of the maximum age
*/ 
define('MAX_AGE', 100);

/**
* Implement hook_menu().
*/
function internet_reception_menu() {
  $items['ireception'] = array(
    'title' => 'Internet reception',
    'page callback' => 'internet_reception_main_function',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE, 
    ); 
  $items['admin/config/system/change_address'] = array(
    'title' => 'Change address',
    'description' => 'Configuration for send message.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('internet_reception_admin_form'),
    'access arguments' => array('administer users'),
    'file' => 'internet_reception.admin.inc',
    'type' => MENU_NORMAL_ITEM,  
  );
  return $items;
}

/**
* Implement hook_form,().
*/
function internet_reception_form($form, &$form_state){
  $form['intro'] = array(
    '#markup' => t('Use this form to send message to us'),
  );
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#required' => TRUE,
  );
  $form['mail'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail'),
    '#required' => TRUE,
    '#elemet_validate' => array('internet_reception_form_validate'),        
  );
  $form['age'] = array(
    '#type' => 'textfield',
    '#title' => t('Age'),
    '#required' => TRUE,
    '#element_validate' => array('internet_reception_form_validate'),
  );
  $form['theme'] = array(
    '#type' => 'textfield',
    '#title' => t('Theme'),
    '#required' => TRUE,
  );
  $form['message'] = array(
    '#type' => 'textarea',
    '#title' => t('Message'),
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form ;
}

//Form validate.
function internet_reception_form_validate(&$form, &$form_state) {
  //Email validation.
  if (!valid_email_address($form_state['values']['mail'])) {
    form_set_error('mail', t('E-mail appears to be invalid.'));
  }
  //Age validation.
   $age_value = $form_state['values']['age'];
  if ($age_value !== '' && (!is_numeric($age_value) || intval($age_value) != $age_value || $age_value <= MIN_AGE || $age_value >=MAX_AGE )) {
    form_set_error('age', t('Age must be a positive integer and less than ' . MAX_AGE . '.'));
  }
}

function internet_reception_main_function() {
  // Obtain a form.
  $form = drupal_get_form('internet_reception_form'); 
  // Rendering form.
  $form = drupal_render($form);
  $form .= 'Fields with "*" is required.';
  return $form;
}

//Add data in message body.
function internet_reception_mail($key, &$message, $params) {
  $message['subject'] = check_plain($params['theme']);
  $message['body'][] = 'Name: ' . check_plain($params['name']);
  $message['body'][] = 'E-mail: ' . check_plain($params['mail']);
  $message['body'][] = 'Age: ' . check_plain($params['age']);
  $message['body'][] = 'Message: ' . check_plain($params['message']);
}
     
/**
* Implement hook_form_submit().
* Submiting form's data.
*/
function internet_reception_form_submit($form, &$form_state) {
  internet_reception_mail_send($form_state['values']);
}
 
function internet_reception_mail_send($form_values) {
  //Create mail contnet.
  $module = 'internet_reception';
  $key = 'contact_message';
  $to = variable_get('new_to', 'hadrosbk@bk.ru');
  $language = language_default();
  $params = $form_values; 
  $from = NULL;
  $send = TRUE;
  $result = drupal_mail($module, $key, $to, $language, $params, $from, $send);
  //Check about successful sending mail.
  if ($result['result'] == TRUE) {
    drupal_set_message(t('Your message has been sent.'));
  }
  else {
    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  }
}